exclude: tests/(data|__snapshots__|samples)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 7c55798a78262d14b2074abf623d8a992ebb70d4  # frozen: v0.16.2
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0  # frozen: v0.49.1
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 41e691678310dfd3833f7ab4e180ddb014310356  # frozen: v2.3.0
  hooks:
  - id: mypy
    args: [--strict]
    exclude: ^tests\/.*
    additional_dependencies:
      - argcomplete
      - types-setuptools
