exclude: tests/data

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/PyCQA/pylint
  rev: v2.17.3
  hooks:
  - id: pylint

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.2
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint-fix
