exclude: tests/(data|__snapshots__|samples)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/PyCQA/pylint
  rev: v3.3.1
  hooks:
  - id: pylint
    additional_dependencies:
      - "pytest==8.3.3"
      - "syrupy==4.7.2"
      - "setuptools"
      - "tree-sitter==0.23.0"
      - "tree-sitter-zeek==0.1.1"

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.2
  hooks:
    - id: ruff-format

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.42.0
  hooks:
  - id: markdownlint-fix
