exclude: tests/(data|__snapshots__|samples)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246  # frozen: v0.15.15
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e  # frozen: v0.48.0
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
    args: [--strict]
    exclude: ^tests\/.*
    additional_dependencies:
      - argcomplete
      - types-setuptools
