exclude: tests/(data|__snapshots__|samples)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: a27a2e47c7751b639d2b5badf0ef6ff11fee893f  # frozen: v0.15.4
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 76b3d32d3f4b965e1d6425253c59407420ae2c43  # frozen: v0.47.0
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: a66e98df7b4aeeb3724184b332785976d062b92e  # frozen: v1.19.1
  hooks:
  - id: mypy
    args: [--strict]
    exclude: ^tests\/.*
    additional_dependencies:
      - argcomplete
      - types-setuptools
